NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import subscriptions

urlpatterns = [
   path('admin/', admin.site.urls),
   path('accounts/', include('allauth.urls')),
   path('posts/', include('news.urls')),
   path('subscriptions/', subscriptions, name='subscriptions'),
]

NewsPaper/news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import (NewsList, NewsDetail, NewsListSearch, PostCreate, PostUpdate,
                    PostDelete, PostCreateAR, PostUpdateAR, PostDeleteAR)
from django.views.decorators.cache import cache_page


urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем статьям у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   path('', cache_page(60*1)(NewsList.as_view()), name='all_news'),
   # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
   # int — указывает на то, что принимаются только целочисленные значения
   path('<int:pk>', NewsDetail.as_view(), name='detail_one_news'),
   path('search', NewsListSearch.as_view(), name='news_search'),
   path('news/create/', PostCreate.as_view(), name='news_create'),
   path('<int:pk>/news/edit/', PostUpdate.as_view(), name='news_create'),
   path('<int:pk>/news/delete/', PostDelete.as_view(), name='news_delete'),
   path('articles/create/', PostCreateAR.as_view(), name='articles_create'),
   path('<int:pk>/articles/edit/', PostUpdateAR.as_view(), name='articles_create'),
   path('<int:pk>/articles/delete/', PostDeleteAR.as_view(), name='articles_delete'),

]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.authorUser}'

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, through='Subscriber', related_name='categories')

    def __str__(self):
        return self.name.title()


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOISES= (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOISES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def __str__(self):
        return f'{self.categoryType.title()}:{self.title.title()}:{self.dateCreation}:{self.text.title()}'

    # def get_absolute_url(self):
    #     return reverse('detail_one_news', args=[str(self.id)])
    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/posts/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )


NewsPaper/templates/all_news.html
{% extends 'default.html' %}

{% load custom_filters %}

{% block title %}
NEWS
{% endblock title %}

{% block content %}
    <h1>Все новости и статьи:</h1>
    <h8>Количество новостей и статей: {{ posts|length }}</h8>
    <hr>
<!--       {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}-->
    {% if perms.news.add_post %}
    <a href="{% url 'articles_create' %}">Добавить статью</a> <a href="{% url 'news_create' %}">Добавить новость</a>
    {% endif %}

    {% if posts %}
        <table>
            <tr>
                <td>Заголовок: </td>
                <td>Дата публикации: </td>
                <td>Содержание: </td>
                <td>Категория поста: </td>
                {% if perms.news.change_post or perms.news.delete_post %}
                <td>Действия:</td>
                {% endif %}
            </tr>

            {% for post in posts|dictsortreversed:"dateCreation" %}
            <tr>
                <td>{{ post.title|censor:"редиска" }}</td>
                <td>{{ post.dateCreation|date:'d M Y' }}</td>
                <td>{{ post.text|truncatewords:20|censor:"редиска"  }}</td>
                <td>{{ post.categoryType }}</td>
                <td>
                    {# Размещаем ссылки #}
                    {% if post.categoryType == "AR" and perms.news.change_post %}
                     <a href="{% url 'articles_create' pk=post.id %}">Изменить</a>
                    {% elif post.categoryType == "NW" and perms.news.change_post %}
                     <a href="{% url 'news_create' pk=post.id %}">Изменить</a>
                    {% endif %}
                    {% if post.categoryType == "AR" and perms.news.delete_post %}
                     <a href="{% url 'articles_delete' post.id %}">Удалить</a>
                    {% elif post.categoryType == "NW" and perms.news.delete_post %}
                     <a href="{% url 'news_delete' post.id %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
         <h3> Новости готовятся к публикации</h3>
    {% endif %}
<!--{# Добавляем пагинацию на страницу #}-->

<!--   {# Информация о предыдущих страницах #}-->
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

<!--   {# Информация о текущей странице #}-->
   {{ page_obj.number }}

<!--   {# Информация о следующих страницах #}-->
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/all_news_search.html
{% extends 'default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
NEWS
{% endblock title %}

{% block content %}
    <h1>Все новости и статьи:</h1>
    <h8>Количество новостей и статей: {{ posts|length }}</h8>
    <hr>
<!-- {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}-->
    <form action="" method="get">
<!--       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}-->
       {{ filterset.form.as_p }}
<!--       {# Добавим кнопку отправки данных формы #}-->
       <input type="submit" value="Найти" />
    </form>

    <hr>

    {% if posts %}
        <table>
            <tr>
                <td>Заголовок: </td>
                <td>Дата публикации: </td>
                <td>Содержание: </td>
            </tr>

            {% for post in posts|dictsortreversed:"dateCreation" %}
            <tr>
                <td>{{ post.title|censor:"редиска" }}</td>
                <td>{{ post.dateCreation|date:'d M Y' }}</td>
                <td>{{ post.text|truncatewords:20|censor:"редиска"  }}</td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
         <h3> Новости готовятся к публикации</h3>
    {% endif %}
<!--{# Добавляем пагинацию на страницу #}-->

<!--   {# Информация о предыдущих страницах #}-->
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

<!--   {# Информация о текущей странице #}-->
   {{ page_obj.number }}

<!--   {# Информация о следующих страницах #}-->
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/articles_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи:</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/articles_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статья:</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/category_list.html
{% extends 'default.html' %}

{% load custom_filters %}

{% block title %}
NEWS
{% endblock title %}

{% block content %}
    <h1>Все новости и статьи:</h1>
    <h8>Количество новостей и статей: {{ posts|length }}</h8>
    <hr>
<!--       {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}-->
    {% if perms.news.add_post %}
    <a href="{% url 'articles_create' %}">Добавить статью</a> <a href="{% url 'news_create' %}">Добавить новость</a>
    {% endif %}

    {% if is_not_subscriber %}
<p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}

    {% if posts %}
        <table>
            <tr>
                <td>Заголовок: </td>
                <td>Дата публикации: </td>
                <td>Содержание: </td>
                <td>Категория поста: </td>
                {% if perms.news.change_post or perms.news.delete_post %}
                <td>Действия:</td>
                {% endif %}
            </tr>

            {% for post in category_news_list|dictsortreversed:"dateCreation" %}
            <tr>
                <td>{{ post.title|censor:"редиска" }}</td>
                <td>{{ post.dateCreation|date:'d M Y' }}</td>
                <td>{{ post.text|truncatewords:20|censor:"редиска"  }}</td>
                <td>{{ post.categoryType }}</td>
                <td>
                    {# Размещаем ссылки #}
                    {% if post.categoryType == "AR" and perms.news.change_post %}
                     <a href="{% url 'articles_create' pk=post.id %}">Изменить</a>
                    {% elif post.categoryType == "NW" and perms.news.change_post %}
                     <a href="{% url 'news_create' pk=post.id %}">Изменить</a>
                    {% endif %}
                    {% if post.categoryType == "AR" and perms.news.delete_post %}
                     <a href="{% url 'articles_delete' post.id %}">Удалить</a>
                    {% elif post.categoryType == "NW" and perms.news.delete_post %}
                     <a href="{% url 'news_delete' post.id %}">Удалить</a>
                    {% endif %}
                </td>
                {% for category in post.category.all %}
                    <a href="{% url 'category_list' category.id %}"{{ category }}
                       {% endfor %}
            </tr>
            {% endfor %}

        </table>
    {% else %}
         <h3> Новости готовятся к публикации</h3>
    {% endif %}
<!--{# Добавляем пагинацию на страницу #}-->

<!--   {# Информация о предыдущих страницах #}-->
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

<!--   {# Информация о текущей странице #}-->
   {{ page_obj.number }}

<!--   {# Информация о следующих страницах #}-->
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> Здравствуйте! Новые статьи за последнюю неделю</h2>
<ul>
    {% for post in posts %}
        <li><a href="http://127.0.0.1:8000{{ post.get_absolute_url }}">{{ post.title }}</a> </li>
    {% endfor %}
</ul>
</body>
</html>

NewsPaper/templates/default.html
<!DOCTYPE html>
<html lang="en">
{% load cache %}
    {% cache 30 header %}
        {% block header %}
        <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>NEWS</title>
        <!-- Favicon-->
        {% load static %}
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
           <div class="container">
               <a class="navbar-brand" href="#">Django flatpages</a>
               <button class="navbar-toggler" type="button" data-toggle="collapse"
                       data-target="#navbarResponsive"
                       aria-controls="navbarResponsive" aria-expanded="false"
                       aria-label="Toggle navigation">
                   <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarResponsive">
                   <ul class="navbar-nav ml-auto">
                       <li class="nav-item active">
                           <a class="nav-link" href="#">Page 1
                               <span class="sr-only">(current)</span>
                           </a>
                       </li>
                       <li class="nav-item">
                           <a class="nav-link" href="/page2/">Page 2</a>
                       </li>
                       <li class="nav-item">
                           <a class="nav-link" href="/page3/">Page 3</a>
                       </li>
                   </ul>
               </div>
           </div>
        </nav>
        {% endblock header %}
    {% endcache %}

        <!-- Page content-->
        <div class="container">
           <div class="row">
               <div class="col-lg-12 text-center">
                   {% block content %}
                   <h1>Все новости:</h1>
                   {{ all_news }}
                   {% endblock content %}
               </div>
           </div>
        </div>
    </body>

</html>

NewsPaper/templates/detail_one_news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
NEWS
{% endblock title %}

{% block content %}
<h1>Новость/Статья:</h1>
<hr>
<table>
        <tr>
            <td>{{ detail_one_news.title|censor:"редиска" }}</td>
        </tr>
        <tr>
            <td align="right">{{ detail_one_news.dateCreation|date:'d M Y' }}</td>
        </tr>
        <tr>
            <td>{{ detail_one_news.text|censor:"редиска" }}</td>
        </tr>
</table>
{% endblock content %}

NewsPaper/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости:</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость:</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/sub_post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> Приветствуем, вышла новая <a href="{{ link  }}">статья</a> в разделе "</h2>
<p>{{ text }}</p>
</body>
</html>

NewsPaper/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}